# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/auth.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11protos/auth.proto\x12\nhelloworld\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\" \n\rLoginResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1d\n\x0cTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"*\n\rTokenResponse\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0b\n\x03sub\x18\x02 \x01(\t2\x89\x01\n\x04\x41uth\x12>\n\x05Login\x12\x18.helloworld.LoginRequest\x1a\x19.helloworld.LoginResponse\"\x00\x12\x41\n\x08Validate\x12\x18.helloworld.TokenRequest\x1a\x19.helloworld.TokenResponse\"\x00\x42\x36\n\x1bio.grpc.examples.helloworldB\x0fHelloWorldProtoP\x01\xa2\x02\x03HLWb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.auth_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033io.grpc.examples.helloworldB\017HelloWorldProtoP\001\242\002\003HLW'
  _globals['_LOGINREQUEST']._serialized_start=33
  _globals['_LOGINREQUEST']._serialized_end=83
  _globals['_LOGINRESPONSE']._serialized_start=85
  _globals['_LOGINRESPONSE']._serialized_end=117
  _globals['_TOKENREQUEST']._serialized_start=119
  _globals['_TOKENREQUEST']._serialized_end=148
  _globals['_TOKENRESPONSE']._serialized_start=150
  _globals['_TOKENRESPONSE']._serialized_end=192
  _globals['_AUTH']._serialized_start=195
  _globals['_AUTH']._serialized_end=332
# @@protoc_insertion_point(module_scope)
